OPERATOR_DIV = '/'
OPERATOR_MUL = '*'
OPERATOR_SUB = '-'
OPERATOR_ADD = '+'
OPERATOR_NE = '~='
OPERATOR_EQ = '=='
OPERATOR_GT = '>'
OPERATOR_GTE = '>='
OPERATOR_LT = '<'
OPERATOR_LTE = '<='
OPERATOR_ASSIGN = '='

TOKEN_EOF = 'EOF'
TOKEN_INTEGER = 'INTEGER'
TOKEN_ADD = 'ADD'
TOKEN_IDENTIFIER = 'IDENTIFIER'

RESERVED_WORDS = ['REPEAT', 'ENDREPEAT', 'LET', 'WHILE', 'ENDWHILE', 'IF', 'THEN', 'ELSE', 'ENDIF', 'BEGIN', 'ENDFUN', ]