##########
# TOKENS #
##########

# Symbols
TOKEN_ADD = 'ADD'
TOKEN_SUB = 'SUB'
TOKEN_MUL = 'MUL'
TOKEN_DIV = 'DIV'
TOKEN_POW = 'POW'
TOKEN_LTE = 'LTE'
TOKEN_GTE = 'GTE'
TOKEN_LT = 'LT'
TOKEN_GT = 'GT'
TOKEN_EQ = 'EQ'
TOKEN_NEQ = 'NEQ'
TOKEN_ASSIGN = 'ASSIGN'
TOKEN_LPAREN = 'LPAREN'
TOKEN_RPAREN = 'RPAREN'
TOKEN_RBRACKET = 'RBRACKET'
TOKEN_LBRACKET = 'LBRACKET'
TOKEN_COMMA = 'COMMA'

# Reserved Words
TOKEN_IMPORT = 'IMPORT'
TOKEN_SYMBOL = 'SYMBOL'
TOKEN_DECLARATIONS = 'DECLARATIONS'
TOKEN_SPECIFICATIONS = 'SPECIFICATIONS'
TOKEN_HCON = 'HCON'
TOKEN_FORWARD = 'FORWARD'
TOKEN_REFERENCES = 'REFERENCES'
TOKEN_MEXTERN = 'MEXTERN'
TOKEN_FUNCTION = 'FUNCTION'
TOKEN_MAIN = 'MAIN'
TOKEN_RETURN = 'RETURN'
TOKEN_BEGINFUNCTION = 'BEGIN_FUNCTION'
TOKEN_ENDFUNCTION = 'END_FUNCTION'
TOKEN_IF = 'IF'
TOKEN_THEN = 'THEN'
TOKEN_ELSE = 'ELSE'
TOKEN_ENDIF = 'ENDIF'
TOKEN_WHILE = 'WHILE'
TOKEN_DO = 'DO'
TOKEN_ENDWHILE = 'ENDWHILE'
TOKEN_REPEAT = 'REPEAT'
TOKEN_UNTIL = 'UNTIL'
TOKEN_ENDREPEAT = 'ENDREPEAT'
TOKEN_DISPLAY = 'DISPLAY'
TOKEN_IMPLEMENTATIONS = 'IMPLEMENTATIONS'
TOKEN_PARAMETERS = 'PARAMETERS'
TOKEN_CONSTANT = 'CONSTANT'
TOKEN_SET = 'SET'
TOKEN_DEFINE = 'DEFINE'

# Types related keywords
TOKEN_OF = 'OF'
TOKEN_TYPE = 'TYPE'
TOKEN_TYPE_ARRAY = 'TYPE_ARRAY'
TOKEN_TYPE_STRUCT = 'TYPE_STRUCT'
TOKEN_TYPE_POINTER = 'TYPE_POINTER'
TOKEN_TYPE_INTEGER = 'TYPE_INTEGER'
TOKEN_TYPE_SHORT = 'TYPE_SHORT'
TOKEN_TYPE_ENUM = 'TYPE_ENUM'

# Value Tokens
TOKEN_IDENTIFIER = 'IDENTIFIER'
TOKEN_INTEGER_LITERAL = 'INTEGER_LITERAL'
TOKEN_STRING_LITERAL = 'STRING_LITERAL'
TOKEN_COMMENT = 'COMMENT'

# Other
TOKEN_EOL = 'EOL'
TOKEN_EOF = 'EOF'

##############
# STATEMENTS #
##############

STATEMENT_IMPORT = 'STMT_IMPORT'
STATEMENT_SYMBOL = 'STMT_SYMBOL'
STATEMENT_DISPLAY = 'STMT_DISPLAY'
STATEMENT_FUNCTION_DEF = 'STMT_FUNCTION_DEF'
STATEMENT_VARIABLE_DEF = 'STMT_VARIABLE_DEF'

#########
# OTHER #
#########

SPECIAL_STRING_CAP = '\"'

