# Symbols

TOKEN_ADD       = 'ADD'
TOKEN_SUB       = 'SUB'
TOKEN_MUL       = 'MUL'
TOKEN_DIV       = 'DIV'
TOKEN_LTE       = 'LTE'
TOKEN_GTE       = 'GTE'
TOKEN_LT        = 'LT'
TOKEN_GT        = 'GT'
TOKEN_EQ        = 'EQ'
TOKEN_NEQ       = 'NEQ'
TOKEN_ASSIGN    = 'ASSIGN'
TOKEN_LPAREN    = 'LPAREN'
TOKEN_RPAREN    = 'RPAREN'

# Reserved Words
TOKEN_SYMBOL = 'SYMBOL'
TOKEN_IDENTIFIER = ''
TOKEN_BEGIN = 'BEGIN'
TOKEN_END = 'END'
TOKEN_IF = 'IF'


# Value Tokens
TOKEN_INTEGER = 'INTEGER'
TOKEN_IDENTIFIER = 'IDENTIFIER'

# Other
TOKEN_EOF = 'EOF'