#  Aaron Roberts
#  CS4308 – Concepts of Programming Language
#  Summer 2017 Online

# simple statement rule definitions

from constants import *

SIMPLE_STATEMENT_RULES = {
    STATEMENT_IMPORT: [TOKEN_IMPORT, TOKEN_STRING_LITERAL],
    STATEMENT_SYMBOL: [TOKEN_SYMBOL, TOKEN_IDENTIFIER, TOKEN_INTEGER_LITERAL],
    STATEMENT_FORWARD_DECLARATIONS: [TOKEN_FORWARD, TOKEN_DECLARATIONS],
    STATEMENT_GLOBAL_DECLARATIONS: [TOKEN_GLOBAL, TOKEN_DECLARATIONS],
    STATEMENT_FUNCTION_DEF: [TOKEN_FUNCTION, TOKEN_IDENTIFIER, TOKEN_RETURN, TOKEN_TYPE, TOKEN_TYPE_INTEGER],
    STATEMENT_VARIABLE_DEF: [TOKEN_DEFINE, TOKEN_IDENTIFIER, TOKEN_OF, TOKEN_TYPE, TOKEN_TYPE_INTEGER],
    STATEMENT_PARAMETER_DEF: [TOKEN_IDENTIFIER, TOKEN_OF, TOKEN_TYPE, TOKEN_TYPE_INTEGER],
    STATEMENT_CONSTANT_DEF: [TOKEN_DEFINE, TOKEN_IDENTIFIER, TOKEN_ASSIGN, TOKEN_INTEGER_LITERAL, TOKEN_OF, TOKEN_TYPE, TOKEN_TYPE_INTEGER],
    STATEMENT_INPUT: [TOKEN_INPUT, TOKEN_STRING_LITERAL, TOKEN_COMMA, TOKEN_IDENTIFIER],
    STATEMENT_SET: [TOKEN_SET, TOKEN_IDENTIFIER, TOKEN_ASSIGN]
}

TYPE_TOKENS = [
    TOKEN_TYPE_INTEGER,
    TOKEN_TYPE_SHORT,
]