from constants import *

SIMPLE_STATEMENT_RULES = {
    STATEMENT_IMPORT: [TOKEN_IMPORT, TOKEN_STRING_LITERAL],
    STATEMENT_SYMBOL: [TOKEN_SYMBOL, TOKEN_IDENTIFIER, TOKEN_INTEGER_LITERAL],
    STATEMENT_FUNCTION_DEF: [TOKEN_FUNCTION, TOKEN_IDENTIFIER, TOKEN_RETURN, TOKEN_TYPE],
    STATEMENT_VARIABLE_DEF: [TOKEN_DEFINE, TOKEN_IDENTIFIER, TOKEN_OF, TOKEN_TYPE]
}